export default  {
    ADD_EDIT_IMAGE: "ADD_EDIT_IMAGE",
    ADD_WM_IMAGE: "ADD_WM_IMAGE",
    INIT_EDIT_VIEW: "INIT_EDIT_VIEW",
    REDRAW: "REDRAW",
    EDIT_DROP: "EDIT_DROP",
    EDIT_DRAG: "EDIT_DRAG",
}