export default  {
    ADD_EDIT_IMAGE: "ADD_EDIT_IMAGE",
    ADD_WM_IMAGE: "ADD_WM_IMAGE",
    ADD_WM_TEXT: "ADD_WM_TEXT",
    INIT_EDIT_VIEW: "INIT_EDIT_VIEW",
    REDRAW: "REDRAW",
    EDIT_DROP: "EDIT_DROP",
    EDIT_DRAG: "EDIT_DRAG",
    EDIT_UP: "EDIT_UP",
    EDIT_OVER: "EDIT_OVER",
    DELETE_SELECTED_SPRITE: "DELETE_SELECTED_SPRITE",
    EXPORT: "EXPORT",
}